### ISSUE TITLE
Is it possible to add  the "solar terms" ?

### ISSUE THREAD

**Issue by XHXIAIEIN** [armandoalonso/timesystem#3]
This is the traditional Chinese lunar calendar, which divides the year into 24 phase according to longitude of sun. 

https://en.wikipedia.org/wiki/Solar_term

![Group+36596](https://github.com/armandoalonso/timesystem/assets/45864744/638d42a2-feee-4fd5-9090-05b938930c43)

this is a definition

```
const SOLARTERMS = ['BeginningOfSpring','RainWater','AwakeningOfInsects','SpringEquinox','PureBrightness','GrainRain','BeginningOfSummer','GrainBuds','GrainInEar','SummerSolstice','MinorHeat','MajorHeat','BeginningOfAutumn','EndOfHeat','WhiteDew','AutumnEquinox','ColdDew','FrostsDescent','BeginningOfWinter','MinorSnow','MajorSnow','WinterSolstice','MinorCold','MajorCold']
```

**Comment by armandoalonso** [comment]
i can certainly look into this, would need to do more research as i'm not familiar, it seems this is a way to break up a year into these "solar terms". i will look into getting this mapped to the existing time system.   

in your data what is the meaning of term? also do you need expressions for solarLongitude ?

**Comment by XHXIAIEIN** [comment]
yeah, Just make it work like Season, WeekDay. Used to detect whether a date is in certain solar terms. Or the event can be triggered when entering solar terms.

It seems good to provide a expressions of Longitude so that the corresponding visual representation can be made based on it without having to manually calculate the angle.

**Comment by armandoalonso** [comment]
👋 Hey so I got a basic implementation working

![solar-term](https://github.com/armandoalonso/timesystem/assets/7579560/5353f088-c9dd-4dcb-8fdc-759468f66972)

currently I am using the English translation, I am not really sure how to handle localization for returned value from an addon? I could add an expression for Chinese name, but it would be the English equivalent of the name  

so like , Xiaohan = Minor Cold
where the specific expression returns Xiaohan instead of Minor Cold

the only thing that is strange is these exist for Korean, Vietnamese, Japanese do you need an expression to return the name in each of these? or just returning the English variant is good? 

How were you intending to use it?

**Comment by armandoalonso** [comment]
also i went by the dates listed here in this table 
![image](https://github.com/armandoalonso/timesystem/assets/7579560/6d2c491f-c410-4509-b1fb-82b69aec030d)

**Comment by armandoalonso** [comment]
I have pushed a branch here: https://github.com/armandoalonso/timesystem/tree/v1.1.0.0

you could test it and see if it is okay? here is the built addon from that branch and the example file

[piranha305_timesystem_example.zip](https://github.com/armandoalonso/timesystem/files/12771809/piranha305_timesystem_example.zip)

I will keep testing a bit too, if you find any issue let me know, if its all good i will release in a few day

**Comment by XHXIAIEIN** [comment]
Thank you so much! only need to provide the English term ~ because expression can easily find it and then localize it. 

### Unify Current as the index value

Can you provide `CurrentSolarTerm` as a index value? and `CurrentSolarTermName` is the en name. This allows it to be positioned better.  For example: 

```
TimeSystem.CurrentSolarTerm           // return 0~23
TimeSystem.CurrentSolarTermName       // return SOLAR_TERMS[n].en
TimeSystem.CurrentSolarTermLongitude  // return SOLAR_TERMS[n].longitude
```

Actually, some expression of the current are not unified like this. such as: *Seasons*, *DayPhase*.

it would be nice if seasons also worked like *CurrentSeason* and *CurrentSeasonName*. Because the Month works the same way: *CurrentMonth* and *CurrentMonthName*


### Calculation method of solar term
The solar terms are not simply divided into 24 parts. It actually has an error of several days. I found the exact calculation Via some articles: It will return the correct solar term date of that year.

The order is also sorted in this order, with the 'Beginning of Spring' at the first.

```js
const SOLAR_TERMS = [
    {'longitude':315,   'minutes':42467,    'en':'Beginning of Spring'},
    {'longitude':330,   'minutes':63836,    'en':'Rain Water'},
    {'longitude':345,   'minutes':85337,    'en':'Awakening of Insects'},
    {'longitude':0,     'minutes':107014,   'en':'Spring Equinox'},
    {'longitude':15,    'minutes':128867,   'en':'Pure Brightness'},
    {'longitude':30,    'minutes':150921,   'en':'Grain Rain'},
    {'longitude':45,    'minutes':173149,   'en':'Beginning of Summer'},
    {'longitude':60,    'minutes':195551,   'en':'Grain Buds'},
    {'longitude':75,    'minutes':218072,   'en':'Grain in Ear'},
    {'longitude':90,    'minutes':240693,   'en':'Summer Solstice'},
    {'longitude':105,   'minutes':263343,   'en':'Minor Heat'},
    {'longitude':120,   'minutes':285989,   'en':'Major heat'},
    {'longitude':135,   'minutes':308563,   'en':'Beginning of Autumn'},
    {'longitude':150,   'minutes':331033,   'en':'End of Heat'},
    {'longitude':165,   'minutes':353350,   'en':'White Dew'},
    {'longitude':180,   'minutes':375494,   'en':'Autumn Equinox'},
    {'longitude':195,   'minutes':397447,   'en':'Cold Dew'},
    {'longitude':210,   'minutes':419210,   'en':'Frosts Descent'},
    {'longitude':225,   'minutes':440795,   'en':'Beginning of Winter'},
    {'longitude':240,   'minutes':462224,   'en':'Minor Snow'},
    {'longitude':255,   'minutes':483532,   'en':'Major Snow'},
    {'longitude':270,   'minutes':504758,   'en':'Winter Solstice'},
    {'longitude':285,   'minutes':0,        'en':'Minor Cold'},
    {'longitude':300,   'minutes':21208,    'en':'Major Cold'},
];

function calculateSolarTerms(year) {
    const baseTimeForYear = 31556925974.7 * (year - 1900) + Date.UTC(1900,0,6,2,5);
    let solarTermsDates = [];
    for(let n = 0; n < 24; n++) {
        let termDate = new Date(baseTimeForYear + SOLAR_TERMS[n].minutes * 60000);
        solarTermsDates.push({ longitude: SOLAR_TERMS[n].longitude, term: SOLAR_TERMS[n].en, date: termDate });
    }
    return solarTermsDates;
}

let solarTerms = calculateSolarTerms(2023);
```

In my game, some animations will be performed at each solar term switch, such as changing the background or triggering events. It is used in the same way as other time attributes, such as month, season, etc.

**Comment by XHXIAIEIN** [comment]
I recommend using a more compact naming of the returned expression without including spaces. This can be more unified with C3 system expressions

```js
const SOLAR_TERMS = [
    {'longitude':315,   'minutes':42467,    'en':'BeginningofSpring'},
    {'longitude':330,   'minutes':63836,    'en':'RainWater'},
    {'longitude':345,   'minutes':85337,    'en':'AwakeningofInsects'},
    {'longitude':0,     'minutes':107014,   'en':'SpringEquinox'},
    {'longitude':15,    'minutes':128867,   'en':'PureBrightness'},
    {'longitude':30,    'minutes':150921,   'en':'GrainRain'},
    {'longitude':45,    'minutes':173149,   'en':'BeginningofSummer'},
    {'longitude':60,    'minutes':195551,   'en':'GrainBuds'},
    {'longitude':75,    'minutes':218072,   'en':'GraininEar'},
    {'longitude':90,    'minutes':240693,   'en':'SummerSolstice'},
    {'longitude':105,   'minutes':263343,   'en':'MinorHeat'},
    {'longitude':120,   'minutes':285989,   'en':'Majorheat'},
    {'longitude':135,   'minutes':308563,   'en':'BeginningofAutumn'},
    {'longitude':150,   'minutes':331033,   'en':'EndofHeat'},
    {'longitude':165,   'minutes':353350,   'en':'WhiteDew'},
    {'longitude':180,   'minutes':375494,   'en':'AutumnEquinox'},
    {'longitude':195,   'minutes':397447,   'en':'ColdDew'},
    {'longitude':210,   'minutes':419210,   'en':'FrostsDescent'},
    {'longitude':225,   'minutes':440795,   'en':'BeginningofWinter'},
    {'longitude':240,   'minutes':462224,   'en':'MinorSnow'},
    {'longitude':255,   'minutes':483532,   'en':'MajorSnow'},
    {'longitude':270,   'minutes':504758,   'en':'WinterSolstice'},
    {'longitude':285,   'minutes':0,        'en':'MinorCold'},
    {'longitude':300,   'minutes':21208,    'en':'MajorCold'},
];
```

**Comment by armandoalonso** [comment]
Okay I think I have it all working in branch https://github.com/armandoalonso/timesystem/tree/v1.1.0.1

Here is the addon - 
[piranha305_timesystem_v1.1.0.1.zip](https://github.com/armandoalonso/timesystem/files/12777004/piranha305_timesystem_v1.1.0.1.zip)

I added some new expressions to make season/phase/solar-term consistent. so they have index expression and name expression

I used the implementation you provided to calculate the solar-term which happens when ever a new year is triggered. 
I use those generated dates to check and trigger solar-term changes. 

I also fixed the bug with current day of the week not triggering for small time changes.

these seem to be working with my testing, let me know if what i did solves your use case?

**Comment by XHXIAIEIN** [comment]
Thanks again for your time! Grateful for providing the index expression so I don't have to escape it again. Greatly improved my efficiency.

I noticed that `TimeSystem.CurrentSolarTerm` always seems to return -1. instead of index value

**Comment by armandoalonso** [comment]
ohh yeah, I see what I did wrong, here is fix, also pushed to branch. 
https://github.com/armandoalonso/timesystem/tree/v1.1.0.2

[piranha305_timesystem-1.1.0.2.zip](https://github.com/armandoalonso/timesystem/files/12781471/piranha305_timesystem-1.1.0.2.zip)

**Comment by XHXIAIEIN** [comment]
Thanks again! Everything is working fine now!

**Comment by armandoalonso** [comment]
thanks again for feedback and suggestions, let me know if you run into any more issues or have more suggestions!

**Comment by XHXIAIEIN** [comment]
Sorry, I suddenly realized that this plugin does not run according to the real time, because it can enter any year. Then solar terms should not be calculated based on real celestial phenomena.Because it can never be right all the time. Calculating equal amounts is the most reasonable.

**Comment by armandoalonso** [comment]
Did you want to change the logic to be based on equal parts? I think we are calculating for the given year? 

https://github.com/armandoalonso/timesystem/blob/main/src/instance.js#L566


then checking the simulated years day based on this calculation? when a new year is triggered, we run this calculation for the new year?

**Comment by XHXIAIEIN** [comment]
> also i went by the dates listed here in this table 

Yes, it makes sense to split by a fixed time the first time you process it, it requires no additional calculations(https://github.com/armandoalonso/timesystem/commit/9a671bccfc86e5db9a83761385cd09d11d9d0838). The algorithm I provided before is based on the longitude and latitude of the real world to calculate the deviation, but in fact, it does not need to be that accurate. Calculating its accuracy is meaningless and will only cause the plug-in to generate additional computing overhead.

**Comment by armandoalonso** [comment]
created https://github.com/armandoalonso/timesystem/issues/6

I can adjust it to use the static dates.
