### ISSUE TITLE
BUG:  Add Date Time action does not update WeekDay

### ISSUE THREAD

**Issue by XHXIAIEIN** [armandoalonso/timesystem#4]
![Snipaste_2023-09-30_20-13-12](https://github.com/armandoalonso/timesystem/assets/45864744/9822665c-5cbd-41de-bc40-924719735b34)

[timesystem-bug.c3p.zip](https://github.com/armandoalonso/timesystem/files/12774616/timesystem-bug.c3p.zip)

**Comment by armandoalonso** [comment]
Yep this was an oversight for how the day was calculated, it was not taking into account small hours, i have a fix for it, ill push it out soon after a bit more testing

**Comment by armandoalonso** [comment]
fixed in branch - https://github.com/armandoalonso/timesystem/tree/v1.1.0.1
will release with solar term changes

**Comment by armandoalonso** [comment]
fix in [v1.1.0.2](https://github.com/armandoalonso/timesystem/releases/tag/piranha305_timesystem-1.1.0.2.c3addon)
